### ISSUE TITLE
改进

### ISSUE THREAD

**Issue by ZPastor** [fofapro/vulfocus#127]
**请简单描述一下需要改进/新增功能**：
web管理界面在拉取漏洞镜像时，总是刷新到第一页内容。需要不停的重复点击各个页面才能拉取镜像
**描述你想要的解决方案**：

**补充内容**：

**Comment by 0nise** [comment]
可以详细说明一下吗？

**Comment by Liiuliu** [comment]
已经解决，点击下载修改不在跳转其它页面
