### ISSUE TITLE
实际使用时WEB上的靶机IP地址和实际不符，建议增加修改功能

### ISSUE THREAD

**Issue by xizyy** [fofapro/vulfocus#135]
希望增加修改“首页”->“附加信息”的IP地址，描述等信息的功能。
因实际使用时发现IP地址不对，把靶机系统开放给其他人使用时很麻烦。

**Comment by xizyy** [comment]
希望增加修改"首页"->"镜像信息"的IP地址、描述等信息的功能。
因实际使用时发现IP地址不对，把靶机系统开放给其他人使用时很麻烦。

**Comment by 0nise** [comment]
这个与启动时的配置有很大关系，启动时设置的IP为Docker的IP。

**Comment by skyroot** [comment]
> 这个与启动时的配置有很大关系，启动时设置的IP为Docker的IP。

我用的是docker方式安装vulfocus，在本mac中运行docker run -d -p 80:80 -v /var/run/docker.sock:/var/run/docker.sock  -e VUL_IP=192.168.1.103 vulfocus/vulfocus，192.168.1.103是另外一台虚机，但是发现镜像下载和容器启动都只是在mac的docker中，192.168.1.103上是空的,不知道是否还需要什么配置？
