### ISSUE TITLE
注册关闭

### ISSUE THREAD

**Issue by mooneee** [fofapro/vulfocus#136]
请问注册怎么才能关闭？

**Comment by 0nise** [comment]
最有效的方式，可以注释 `vulfocus-api/vulfocus/urls.py` 文件中的 

```
router.register('user/register', UserRegView, base_name='register')
```

**Comment by mooneee** [comment]
已经解决了。多谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: r4v3zn <notifications@github.com&gt;
发送时间: 2020年12月21日 12:30
收件人: fofapro/vulfocus <vulfocus@noreply.github.com&gt;
抄送: mooneee <276615508@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[fofapro/vulfocus] 注册关闭 (#136)





 
最有效的方式，可以注释 vulfocus-api/vulfocus/urls.py 文件中的
 router.register('user/register', UserRegView, base_name='register')
