### ISSUE TITLE
靶机docker 镜像启动后立即访问地址失败 需要重新刷新几次或等待几秒才能访问

### ISSUE THREAD

**Issue by skyroot** [fofapro/vulfocus#141]
**请简单描述一下需要改进/新增功能**：
镜像启动后立即访问地址失败,要重新刷新几次才能访问靶机，用户体验不太好

**描述你想要的解决方案**：
建议在前端加个进度条显示，后端加个检测容器启动状态接口
**补充内容**：

**Comment by 0nise** [comment]
本身在启动之后容器是正常启动的，慢的主要原因是某些大型的应用启动慢，导致无法访问。
