### ISSUE TITLE
页面删除按钮问题

### ISSUE THREAD

**Issue by JesonZHY** [fofapro/vulfocus#142]
首页容器启动后的删除按钮的icon将按钮的上下距离拉大，导致页面card布局出现问题
![微信图片_20210111165900](https://user-images.githubusercontent.com/34958920/104161752-55d23380-542e-11eb-9304-f5ba22b5b49e.png)

**Comment by 0nise** [comment]
可能是由于页面布局的问题，下个版本处理

**Comment by 0nise** [comment]
v0.3.2.2已修复
