### ISSUE TITLE
建议-前端终端管理功能

### ISSUE THREAD

**Issue by RedTeamWing** [fofapro/vulfocus#155]
前端可以加一个shell的功能，方便快速管理容器。

**Comment by boluoha** [comment]
新版本启动docker 有问题，无法下载漏洞环境。
漏洞环境无法指定端口，直接绑定死了，不太友好。

**Comment by 0nise** [comment]
> 新版本启动docker 有问题，无法下载漏洞环境。
> 漏洞环境无法指定端口，直接绑定死了，不太友好。

能具体说明哪个镜像吗？端口启动是随机的不会不会写死，可以检查一下是否配置了 Docker URL。

**Comment by boluoha** [comment]
排查了一下，是我安装的docker版本过低。基本解决了下载问题。
如何自己指定docker端口？因为服务只开放了特定的端口范围，不指定无法访问。

**Comment by boluoha** [comment]
修改随机端口在哪里修改，我这边想把随机端口定义到特定范围内，如何修改。

**Comment by 0nise** [comment]
> 修改随机端口在哪里修改，我这边想把随机端口定义到特定范围内，如何修改。

随机端口位于 `vulfocus-api\tasks\tasks.py` 文件中第 287 行。

**Comment by boluoha** [comment]
thanks，it work
