### ISSUE TITLE
新建的vulfocus一键同步后提示同步成功，镜像页面空白

### ISSUE THREAD

**Issue by aisnnu** [fofapro/vulfocus#160]
**报错信息**
![image](https://user-images.githubusercontent.com/41133745/121659457-e6439b80-cad4-11eb-80ad-7495b8438258.png)

**操作系统**： 

**内核版本**：

**Python 环境版本**：

**Vulfocus 版本**：
 v0.3.2.4

**详细报错信息或堆栈报错信息**：

**Comment by 0nise** [comment]
BUG已经修复，重新同步漏洞信息
