### ISSUE TITLE
一键同步后提示成功，镜像页面空白

### ISSUE THREAD

**Issue by aisnnu** [fofapro/vulfocus#161]
**报错信息**
![image](https://user-images.githubusercontent.com/41133745/121659720-29057380-cad5-11eb-830a-3ea21b5f33fa.png)

**操作系统**： 
Kali2021.2
**内核版本**：
Linux 5.10.0-kali8-amd64 #1 SMP Debian 5.10.40-1kali1 (2021-05-31) x86_64 GNU/Linux

**Python 环境版本**：
python3.9.2
**Vulfocus 版本**：
 v0.3.2.4

**详细报错信息或堆栈报错信息**：

**Comment by 0nise** [comment]
BUG已修复，请重新点击 一键同步按钮
