### ISSUE TITLE
镜像漏洞描述部分乱码

### ISSUE THREAD

**Issue by aisnnu** [fofapro/vulfocus#163]
**报错信息**
![image](https://user-images.githubusercontent.com/41133745/121661256-98c82e00-cad6-11eb-80e7-d94a066ee2bd.png)

**操作系统**： 
kali2021.2
**内核版本**：
Linux  5.10.0-kali8-amd64 #1 SMP Debian 5.10.40-1kali1 (2021-05-31) x86_64 GNU/Linux

**Python 环境版本**：
Python3.9
**Vulfocus 版本**：
 v0.3.2.4

**详细报错信息或堆栈报错信息**：

**Comment by 0nise** [comment]
BUG 已修复，重新更新漏洞信息。
