### ISSUE TITLE
漏洞镜像自动同步后不全部下载，期待加一个一键下载的按钮

### ISSUE THREAD

**Issue by aisnnu** [fofapro/vulfocus#165]
**请简单描述一下需要改进/新增功能**：
在漏洞镜像一键同步后，只是同步下来了存在的漏洞，还是需要逐个下载，后期可以加一个一键下载所有镜像的功能
**描述你想要的解决方案**：
最理想的就是一键同步结束后自动开始一键下载所有漏洞镜像
**补充内容**：

**Comment by 0nise** [comment]
在设置模块里面有选项是可以开启是否自动下载的
