### ISSUE TITLE
添加数据导出功能或支持数据迁移

### ISSUE THREAD

**Issue by RedTeamWing** [fofapro/vulfocus#17]
平台的镜像数据怎么保存到主机上。

**Comment by 0nise** [comment]
v0.2.0 功能已经实现

**Comment by 0nise** [comment]
映射宿主机 db 到 docker 中：

`docker create -p 80:80 -v /var/run/docker.sock:/var/run/docker.sock -v db.sqlite3:/vulfocus-api/db.sqlite3 -e VUL_IP=xxx.xxx.xxx.xxx vulfocus/vulfocus:latest`

启动
`docker start container id`
