### ISSUE TITLE
无法注册普通用户

### ISSUE THREAD

**Issue by sysyz** [fofapro/vulfocus#192]
**报错信息**   服务器内部错误，请联系管理员

**操作系统**： Linux test 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Vulfocus 版本**：0.3.2.7

![](https://img.secshell.cn/imgs/20210830205502.png)

**Comment by Liiuliu** [comment]
已经解决，可以更新版本，关掉邮箱验证

**Comment by ZMR0zhangmouren** [comment]
老哥，docker如何更新版本

**Comment by ZMR0zhangmouren** [comment]
> 已经解决，可以更新版本，关掉邮箱验证

老哥docker版本的 vulfocus如何升级更新或者关闭邮箱？注释掉就行么？

**Comment by Liiuliu** [comment]
@ZMR0zhangmouren   更新镜像，系统设置里可以关闭邮箱验证功能

**Comment by Liiuliu** [comment]
已修复

**Comment by ZMR0zhangmouren** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
