### ISSUE TITLE
忘记密码功能，提示“您所绑定邮箱不可达，请验证该邮箱是否存在”

### ISSUE THREAD

**Issue by smartzh** [fofapro/vulfocus#194]
**报错信息**

注册用户正常，正常发送激活邮箱。
但是忘记密码功能，就报错“您所绑定邮箱不可达，请验证该邮箱是否存在”
没有报错的日志

**操作系统**： 

**内核版本**：

**Python 环境版本**：

**Vulfocus 版本**：

2.3.7

**详细报错信息或堆栈报错信息**：

**Comment by 0nise** [comment]
已支持邮箱登陆
