### ISSUE TITLE
文件形式上传tar包，会报413错误

### ISSUE THREAD

**Issue by TC130** [fofapro/vulfocus#2]
可能是nginx默认的配置问题，建议在镜像中调整
<img width="493" alt="0521c19867b0ebe0d8f18b3156067bd" src="https://user-images.githubusercontent.com/8563648/80066239-2876ea00-856e-11ea-8fb7-b1ecda6f6654.png">
<img width="447" alt="d2cab59a316bdfb8dcc322ecd70cb60" src="https://user-images.githubusercontent.com/8563648/80066245-2ad94400-856e-11ea-9546-b600980d9c28.png">
![image](https://user-images.githubusercontent.com/8563648/80066266-33ca1580-856e-11ea-82e3-ac8b14048b05.png)

**Comment by 0nise** [comment]
BUG， 已经修复，请通过以下命令进行更新。

```
docker pull vulfocus/vulfocus:latest

docker pull vulfocus/vulfocus:0.1.2
```

下载最新版本的 Docker 镜像，然后进行启动容器。

```
 docker run -d -p 80:80 -v /var/run/docker.sock:/var/run/docker.sock  -e VUL_IP=xxx.xxx.xxx.xxx vulfocus/vulfocus
```

**Comment by TC130** [comment]
赞
