### ISSUE TITLE
注册新账户member没有同步admin的靶场镜像

### ISSUE THREAD

**Issue by sysyz** [fofapro/vulfocus#208]
**操作系统**： ubuntu

**Vulfocus 版本**：0.3.2.9

1、注册新账户 member没有同步admin账户的靶场镜像

2、admin启动在首页启动靶场，靶场排序出现错版

**Comment by Liiuliu** [comment]
@sysyz  第一个问题新注册的用户需要通关一个入门镜像才可以解锁所有镜像，新注册用户进入后会有提示的详细看下提示就好了。  第二个问题可以截图看看么
