### ISSUE TITLE
arm架构运行报错

### ISSUE THREAD

**Issue by linuxdy** [fofapro/vulfocus#223]
**系统环境**
Linux kali 5.10.0-kali3-arm64 #1 SMP Debian 5.10.12-1kali1 (2021-02-03) aarch64 GNU/Linux

**报错内容**：

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
1b8bcf0e6b028506c9ac1a3d2e59a2ca2735cacee97d1c0d649435ac7204b838

![image](https://user-images.githubusercontent.com/50064309/142839052-40b16699-ce25-4973-86fb-cd9108980142.png)

**Comment by 0nise** [comment]
vulfocus目前不支持arm
