### ISSUE TITLE
Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by longzaizai001** [fofapro/vulfocus#225]
Encountered errors while bringing up the project.

**Comment by longzaizai001** [comment]
Encountered errors while bringing up the project.    场景启动失败  是因为内存的原因吗

**Comment by x98zy** [comment]
在本地服务器删除已有的vulfocus/httpd-apache_parsing_vulnerability这个镜像，然后再docker pull vulfocus/httpd-apache_parsing_vulnerability重新拉取，下载完之后vulfocus/httpd-apache_parsing_vulnerability的镜像id应该为2cd7a15f081b

**Comment by x98zy** [comment]
> Encountered errors while bringing up the project. 场景启动失败 是因为内存的原因吗

在本地服务器删除已有的vulfocus/httpd-apache_parsing_vulnerability这个镜像，然后再docker pull vulfocus/httpd-apache_parsing_vulnerability重新拉取，下载完之后vulfocus/httpd-apache_parsing_vulnerability的镜像id应该为2cd7a15f081b

**Comment by longzaizai001** [comment]
感谢
