### ISSUE TITLE
log4j如何验证修复结果？

### ISSUE THREAD

**Issue by Changego** [fofapro/vulfocus#228]
**请简单描述一下需要改进/新增功能**：
您好，有点懵 log4j如何验证修复结果？
flag 我配置了 flag-{1111}
参数如下，试了好多种无效果。
POST /hello?payload=1111 HTTP/1.1
Host: 192.168.1.62:9200
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Connection: close
**描述你想要的解决方案**：
 请教下，参数怎么拼？感谢。
**补充内容**：

**Comment by 0nise** [comment]
`POST` 发包，Body参数名为 `payload `

**Comment by Changego** [comment]
老板，可以发个包例子？这样的。
POST /hello?payload=1111 HTTP/1.1
Host: 192.168.1.62:9200
Accept-Encoding: gzip, deflate
Accept: /
Accept-Language: en
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Connection: close

**Comment by 0nise** [comment]
```
POST /hello HTTP/1.1
Host: 192.168.1.62:9200
Accept-Encoding: gzip, deflate
Content-Type: application/x-www-form-urlencoded
Accept: /
Accept-Language: en
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Connection: close

payload=1111
```

**Comment by Changego** [comment]
多谢
