### ISSUE TITLE
无法找回账号

### ISSUE THREAD

**Issue by ghost** [fofapro/vulfocus#230]
目前在线fulfocus只能通过账号登录，用户一但忘记账号, 根本无法登录(**找回密码只能更新密码, 还是不知道账号，无法登录**)

建议支持账号或邮箱的方式登录，或者增添通过邮箱找回账号的功能。

**Comment by 0nise** [comment]
会在近期更新

**Comment by 0nise** [comment]
已支持邮箱登陆
