### ISSUE TITLE
本地部署迁移时报错

### ISSUE THREAD

**Issue by zhangxianhongxianhong** [fofapro/vulfocus#233]
**请简单描述一下需要改进/新增功能**：
自己部署时在服务器上执行这三句后
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
在本地执行python manage.py migrate时会报错，column "user_id" of relation "layout_user_fav" already exists
由于layout_image依赖django user
后来发现在本地执行时，先执行python3 manage.py makemigrations user再执行以上三句是ok的

**描述你想要的解决方案**：

**补充内容**：

**Comment by sunzhengyu99** [comment]
师傅能请教下本地部署的问题吗

**Comment by x98zy** [comment]
一般迁移报错的原因都是因为本地的migrations下的迁移记录和数据库中迁移记录不同步造成的，可重点检查数据中相应的表结构是否和models是否同步
