### ISSUE TITLE
Log4j2远程命令执行——在线容器 进行dnslog插入不回显,报错 地址栏显示xxx/hello?payload=111

### ISSUE THREAD

**Issue by wjl110** [fofapro/vulfocus#241]
**报错信息**
Log4j2远程命令执行——在线容器 进行dnslog插入不回显,报错 地址栏显示xxx/hello?payload=111
**操作系统**： 
Mac Big Sur6,3
**内核版本**：

**Python 环境版本**：

**Vulfocus 版本**：
在线
**详细报错信息或堆栈报错信息**：
504

**Comment by Liiuliu** [comment]
编码一下请求参数

**Comment by Mulburryrelic63** [comment]
> 编码一下请求参数

thanks😁
