### ISSUE TITLE
靶场链接可以做成超链接吗?每次都要复制粘贴,复制粘贴,复制粘贴,而且碰见地址宕机的情况,就要一直复制粘贴,直到靶场出现........还有就是,有多个端口的靶场,手都要点痛,眼睛也是要非常仔细才不会错

### ISSUE THREAD

**Issue by wjl110** [fofapro/vulfocus#242]
**请简单描述一下需要改进/新增功能**：
就想要个靶场链接
**描述你想要的解决方案**：
重定向
**补充内容**：
如题

**Comment by Liiuliu** [comment]
暂时没有办法，因为很多靶场中可能有很多非 HTTP 协议的，如果都根据 HTTP 做成链接的话可能会出现问题。

**Comment by Mulburryrelic63** [comment]
> 暂时没有办法，因为很多靶场中可能有很多非 HTTP 协议的，如果都根据 HTTP 做成链接的话可能会出现问题。
3ks
