### ISSUE TITLE
所有的webmin容器都是这个样子了

### ISSUE THREAD

**Issue by wjl110** [fofapro/vulfocus#243]
**报错信息**
![image](https://user-images.githubusercontent.com/53851034/154028041-c72431b6-79fd-437a-af26-ec8847683f38.jpeg)![image](https://user-images.githubusercontent.com/53851034/154028060-fd7053c0-b2be-466c-a27b-972370075154.jpeg)
**操作系统**： 
Macos bigsur 6.3
**内核版本**：

**Python 环境版本**：

**Vulfocus 版本**：在线容器

**详细报错信息或堆栈报错信息**：如图

**Comment by Liiuliu** [comment]
加 https://

**Comment by Liiuliu** [comment]
@Mulburryrelic63

**Comment by Mulburryrelic63** [comment]
> @Mulburryrelic63 

收到
