### ISSUE TITLE
报错服务器内部错误

### ISSUE THREAD

**Issue by Ethereal-boy** [fofapro/vulfocus#246]
**报错信息**：服务器内部错误，请联系管理员

**操作系统**： ubuntu18.04

**内核版本**：5.4.0-100-generic

**Python 环境版本**：pyhton3

**Vulfocus 版本**：3.2.11

**详细报错信息或堆栈报错信息**：[2022-02-18 00:48:17,904: INFO/MainProcess] Connected to redis://127.0.0.1:6379/0
[2022-02-18 00:48:17,931: INFO/MainProcess] mingle: searching for neighbors
[2022-02-18 00:48:18,979: INFO/MainProcess] mingle: all alone
[2022-02-18 00:48:19,017: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2022-02-18 00:48:19,017: INFO/MainProcess] celery@2bad3064d0b5 ready.
[2022-02-18 00:48:23,609: INFO/Beat] beat: Starting...
![image](https://user-images.githubusercontent.com/68326147/154532259-7badb372-129e-4560-bb02-bde350aae6e6.png)

**Comment by Liiuliu** [comment]
目前一键同步无法使用，需要更改url 或者等待fofa.so恢复，或者去vulfocus.io 上做漏洞验证。 添加按钮上有本地导入功能可以直接导入本地镜像

**Comment by Tivon1995** [comment]
您好，现在无法自定义节点了，我该如何修改rul
![image](https://user-images.githubusercontent.com/57749670/155675439-447e1cb9-debb-4c48-a59d-5921028dc8cb.png)

**Comment by Tivon1995** [comment]
您刚才提到需要修改url，改成什么地址呢

**Comment by x98zy** [comment]
将项目目录下vulfocus-api/dockerapi/views.py 1576行的vulfocus.fofa.so改成vulfocus.io
![微信截图_20220228103805](https://user-images.githubusercontent.com/43631350/155914920-abb221d3-b6c7-4368-8b1d-bf49f6d90265.png)

**Comment by x98zy** [comment]
> 您好，现在无法自定义节点了，我该如何修改rul ![image](https://user-images.githubusercontent.com/57749670/155675439-447e1cb9-debb-4c48-a59d-5921028dc8cb.png)

那个是网卡，需要你先在后台添加后才能选中
![网卡](https://user-images.githubusercontent.com/43631350/155915337-2e59f8c7-bcdc-4baf-abba-ef407eed476f.png)

**Comment by Tivon1995** [comment]
感谢大佬指点，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月28日(星期一) 上午10:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fofapro/vulfocus] 报错服务器内部错误 (Issue #246)





 
将项目目录下vulfocus-api/dockerapi/views.py 1576行的vulfocus.fofa.so改成vulfocus.io
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tivon1995** [comment]
感谢管理大大，我以及弄明白了，谢谢管理的回复，祝生活愉快，事事顺利。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fofapro/vulfocus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fofapro/vulfocus] 报错服务器内部错误 (Issue #246)





  
您好，现在无法自定义节点了，我该如何修改rul 
  
那个是网卡，需要你先在后台添加后才能选中
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 0nise** [comment]
已修复

**Comment by 2829632740** [comment]
我也出现了服务器内部错误    但是我没有找到  vulfocus-api 这个文件  请问该怎么办

**Comment by 2829632740** [comment]
![image](https://user-images.githubusercontent.com/89339284/166100773-95c299be-a367-47c4-9327-3d689a01b927.png)

**Comment by whuchenshuo** [comment]
> ![image](https://user-images.githubusercontent.com/89339284/166100773-95c299be-a367-47c4-9327-3d689a01b927.png)

需要先 docker exec -it "container_id" /bin/sh进入容器内部后再查看文件夹

**Comment by fty593041412** [comment]
现在修改后也不能同步

**Comment by hiyoshiy** [comment]
我也不能同步，试过vulfocus.fofa.so改成vulfocus.io以及vulfocus.cn都不能成功

**Comment by guandonxin** [comment]
求教，目前一键同步可以用了吗？
<img width="1226" alt="6" src="https://github.com/user-attachments/assets/b6eeef00-c1ac-4fc5-9a47-22d90ed9616b">
