### ISSUE TITLE
vulfocus/webgrind-cve_2018_12909 镜像环境问题

### ISSUE THREAD

**Issue by horseworkbench** [fofapro/vulfocus#248]
**报错信息** : 502 Bad Gateway

**操作系统**： windows

**内核版本**：

**Python 环境版本**：3.8

**Vulfocus 版本**：

**详细报错信息或堆栈报错信息**：
502 Bad Gateway,输入payload或者是不输入都是显示502 Bad Gateway，当时的猜测payload为
http://123.58.236.76:13346/webgrind/index.php?op=fileviewer&file=/etc/passwd

**Comment by wsatan** [comment]
应该为http://123.58.236.76:13346/index.php?op=fileviewer&file=/etc/passwd
