### ISSUE TITLE
希望官方能优化一下服务器,主页,容器都加载不出来

### ISSUE THREAD

**Issue by wjl110** [fofapro/vulfocus#252]
**请简单描述一下需要改进/新增功能**：
希望官方能优化一下服务器,主页,容器都加载不出来
**描述你想要的解决方案**：
希望官方能优化一下服务器,主页,容器都加载不出来
**补充内容**：
<img width="1314" alt="图片" src="https://user-images.githubusercontent.com/53851034/156110097-8fccd560-b5c6-42d5-b4e4-9ca0014eb979.png">

**Comment by wjl110** [comment]
确定自己的网络和cdn解析都没问题,其他网站也能正常访问浏览

**Comment by wjl110** [comment]
<img width="1199" alt="图片" src="https://user-images.githubusercontent.com/53851034/156110427-52b6ef39-4e9b-417a-80cb-c0c0d55993e2.png">

**Comment by wjl110** [comment]
1.firefox

<img width="1315" alt="图片" src="https://user-images.githubusercontent.com/53851034/156111303-5e0c0695-ad3f-4c6f-9f40-c46ecc8b74a2.png">

**Comment by 0nise** [comment]
已经优化解决，引入CDN
