### ISSUE TITLE
场景功能地址有显示bug

### ISSUE THREAD

**Issue by IsolatoWen** [fofapro/vulfocus#254]
我在使用docker安装时，填写的虚拟机地址是192.168.203.141，然后在另一个网络环境，我的地址变成了192.168.0.114，这时输入0.114地址能正常访问，开启靶场镜像也是正常0.114的地址，但是在启动场景时，显示的地址是203.141+端口号 ，直接访问无法访问，将地址改成0.114+分配的端口号可正常访问

![图片](https://user-images.githubusercontent.com/44858081/156487382-41d99764-55a5-472e-a3e7-46da0abc13f7.png)
![图片](https://user-images.githubusercontent.com/44858081/156487464-fa310313-e1bb-4e14-a814-1de86fb53cdf.png)
![图片](https://user-images.githubusercontent.com/44858081/156487506-394a05d1-3b7f-410a-b70d-01ae528006db.png)
![图片](https://user-images.githubusercontent.com/44858081/156487570-cdad12f8-afb9-4e8b-b9f5-af3e2df5fe3d.png)
![图片](https://user-images.githubusercontent.com/44858081/156487583-1f31268f-ab12-4b01-bcb8-17b81d5ee1c0.png)

**Comment by x98zy** [comment]
这个是因为镜像的ip地址我们会根据前端的请求ip来动态变化，而场景的IP地址是我们根据你启动镜像时指定的VUL_IP环境变量来确定，这个VUL_IP没变，你的场景的访问ip也不会变化

**Comment by x98zy** [comment]
你可以重新设置一下docker 容器中VUL_IP这个环境变量，将它设置你现在局域网下的ip,后期我们官方会修改这一问题
