### ISSUE TITLE
zentaopms-cnvd_2020_121325:latest 在线镜像无法获取后台403forbidden

### ISSUE THREAD

**Issue by wjl110** [fofapro/vulfocus#260]
**报错信息**
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/53851034/156777587-384b9fd4-7463-4bd6-949c-b1929b9a3ff9.png">

**操作系统**： 

**内核版本**：

**Python 环境版本**：

**Vulfocus 版本**：
在线
**详细报错信息或堆栈报错信息**：
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/53851034/156777765-adced815-424c-42e0-aa7e-6ef25f202cd0.png">

**Comment by wsatan** [comment]
已修改
