### ISSUE TITLE
wordpress-cve_2019_9978:latest 镜像打开自动跳转到8000端口,并且无法连接

### ISSUE THREAD

**Issue by wjl110** [fofapro/vulfocus#263]
**报错信息**
<img width="884" alt="image" src="https://user-images.githubusercontent.com/53851034/156925918-1b166d34-2814-403d-a570-ab24cd8184cd.png">
<img width="589" alt="image" src="https://user-images.githubusercontent.com/53851034/156925952-a9d698c4-0b64-455f-bbb4-284506ba6c79.png">

**操作系统**： 

**内核版本**：

**Python 环境版本**：

**Vulfocus 版本**：

**详细报错信息或堆栈报错信息**：

**Comment by wsatan** [comment]
已解决
