### ISSUE TITLE
名称: vulfocus/armhf22:latest 在线/tmp文件夹值为空,没有flag

### ISSUE THREAD

**Issue by wjl110** [fofapro/vulfocus#264]
**请简单描述一下需要改进/新增功能**：
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/53851034/156933638-1e70ce34-0ee8-45c2-bfe0-063657e46caa.png">
<img width="687" alt="image" src="https://user-images.githubusercontent.com/53851034/156933702-f87a215d-aab0-4b66-9fb0-4605b5fbd1bf.png">

**描述你想要的解决方案**：
添加flag
**补充内容**：
/tmp值为空

**Comment by wjl110** [comment]
用爬虫把服务器爬了一遍,只找到了两个flags文件,但并不是flag

**Comment by anxianlang** [comment]
已修改

**Comment by wjl110** [comment]
> 已修改

但是我再次进入靶场,在/tmp目录下也没有找到flag啊...
<img width="875" alt="image" src="https://user-images.githubusercontent.com/53851034/157622187-bb846dc4-4b87-4ce9-b7f2-5eeba264d0d4.png">

**Comment by anxianlang** [comment]
该镜像暂时关闭flag

**Comment by wjl110** [comment]
收到

> 该暂时关闭flag
