### ISSUE TITLE
文档有一处错别字

### ISSUE THREAD

**Issue by tw0cat** [fofapro/vulfocus#280]
**请简单描述一下需要改进/新增功能**：发现有一处错别字，如下图，此处的"进行管理"实际应该是"镜像管理"

**描述你想要的解决方案**：修正即可

**补充内容**：

![image](https://user-images.githubusercontent.com/97861100/162351666-6fd62514-1fd7-41c0-9ed8-3c54add06493.png)

**Comment by 0nise** [comment]
已更正
