### ISSUE TITLE
Monstra文件上传题不能解析上传的php7文件

### ISSUE THREAD

**Issue by Anthonylsd** [fofapro/vulfocus#282]
**请简单描述一下需要改进/新增功能**：
Monstra文件上传题不能解析上传的php7文件
<img width="798" alt="截屏2022-04-22 下午10 35 53" src="https://user-images.githubusercontent.com/33222731/164736431-90ebb8f8-8904-4493-a9fe-e657a7ca304b.png">

**描述你想要的解决方案**：
修改配置文件：/etc/apache2/mods-enabled/php7.0.conf
增加FilesMatch模块，使其能够解析php7文件
**补充内容**：

**Comment by marskzj** [comment]
此漏洞为白名单，可以上传.phar解析，您在漏洞复现遇到瓶颈时，可参照writeup来复现。
