### ISSUE TITLE
安装报错Error: Request failed with status code 502怎么整？

### ISSUE THREAD

**Issue by vikiName** [fofapro/vulfocus#283]
**报错信息**
Error: Request failed with status code 502
**操作系统**： 
centos7.5
**Python 环境版本**：
python3.7
**Vulfocus 版本**：
lastest
**详细报错信息或堆栈报错信息**：
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/19499467/166132021-cc16bcc7-69df-47d4-bad9-c62713888aae.png">

**Comment by bobipoppy** [comment]
重启镜像容器就可以了
