### ISSUE TITLE
discuz 两个容器的错误

### ISSUE THREAD

**Issue by findlakes** [fofapro/vulfocus#291]
discuz 命令执行 （wooyun-2010-080723）    mysql没启动起来  所以页面根本无法访问
----------------------------------------------------------------------------------------------------
discuz-x3.4 文件删除    容器启动后  进行安装的时候报错。  

@@@@@@@@@@@@@@@@@@@@@@@@
以上两个后来我又试了试 都没问题了    都打通了  该问题关闭吧。

**Comment by findlakes** [comment]
这个没问题  可以打   之前我想错了   。该问题 关闭吧

**Comment by wooluo** [comment]
怎么打通的，数据库都连不上，请问
