### ISSUE TITLE
一键同步后提示成功，镜像页面空白

### ISSUE THREAD

**Issue by fengyijiu520** [fofapro/vulfocus#307]
![1664537819281](https://user-images.githubusercontent.com/114742206/193261603-3d89de10-b74a-483c-832c-c5454a5078b7.jpg)
**报错信息** [一键同步后提示成功，镜像页面空白]

**操作系统**： kali2020.3

**内核版本**：Linux version 5.18.0-kali5-amd64 (devel@kali.org) (gcc-11 (Debian 11.3.0-3) 11.3.0, GNU ld (GNU Binutils for Debian) 2.38) #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07)

**Python 环境版本**：Python 3.10.7

**Vulfocus 版本**：
v 0.3.2.11
**详细报错信息或堆栈报错信息**：

**Comment by QiLin713** [comment]
问一下咋处理的啊

**Comment by 0nise** [comment]
#304
