### ISSUE TITLE
网卡管理模块 “网卡名称不能为空”

### ISSUE THREAD

**Issue by QiLin713** [fofapro/vulfocus#309]
**报错信息** 网卡管理模块  新增网卡信息 提示 网卡名称不能为空

**操作系统**： centos7

**内核版本**：3.10.0-1160.76.1.el7.x86_64

**Python 环境版本**：python3.6

**Vulfocus 版本**： latest

**详细报错信息或堆栈报错信息**：
![image](https://user-images.githubusercontent.com/114209902/195773749-ce609b15-6dd8-4513-802a-377e32779a9f.png)

**Comment by 0nise** [comment]
确认 Vulfocus 中有正确配置Docker链接以及Docker服务正常运行
