### ISSUE TITLE
新建的vulfocus一键同步后提示同步成功，镜像页面空白

### ISSUE THREAD

**Issue by mrq0156** [fofapro/vulfocus#315]
**报错信息**

**操作系统**： 
Ubuntu20.04

**内核版本**：
5.15.0

**Python 环境版本**：

**Vulfocus 版本**：
v03.2.11

**详细报错信息或堆栈报错信息**：
![F[Z[~L{N[ECCRV)X~N27846(1).png](https://user-images.githubusercontent.com/87071832/200755763-0e780c0c-6a61-4a05-9f1a-fc049f2f74da.png)

**Comment by mrq0156** [comment]
Access to XMLHttpRequest at 'https://hub.docker.com/api/content/v1/products/search?page_size=50&q=vulfocus%2F&type=image' from origin 'http://192.168.10.11' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by likewhite** [comment]
https://github.com/fofapro/vulfocus/discussions/304
