### ISSUE TITLE
vulfocus功能优化建议

### ISSUE THREAD

**Issue by Leeboble** [fofapro/vulfocus#32]
1、漏洞信息模块：侧边栏可以添加漏洞信息模块，由使用者自己编辑。编辑的漏洞信息可以关联到镜像信息中。

2、添加web terminal功能：1、方便进行命令端操作；2、使用者学习漏洞修复时可以直接通过web terminal操作。

3、添加分组功能：镜像组管理-->添加镜像组名称-->打开镜像组-->添加docker镜像

**Comment by 0nise** [comment]
在 0.2.2 版本中会计划新增：漏洞信息模块（侧边栏可以添加漏洞信息模块，由使用者自己编辑。编辑的漏洞信息可以关联到镜像信息中）
在 0.3.0 版本中会计划新增：分组功能，可定义分配网络段以及自定义组合漏洞环境。

**Comment by vc1** [comment]
> 在 0.2.2 版本中会计划新增：漏洞信息模块（侧边栏可以添加漏洞信息模块，由使用者自己编辑。编辑的漏洞信息可以关联到镜像信息中）
> 在 0.3.0 版本中会计划新增：分组功能，可定义分配网络段以及自定义组合漏洞环境。

建议内置一些镜像，一键拉取启动

**Comment by 0nise** [comment]
> > 在 0.2.2 版本中会计划新增：漏洞信息模块（侧边栏可以添加漏洞信息模块，由使用者自己编辑。编辑的漏洞信息可以关联到镜像信息中）
> 
> > 在 0.3.0 版本中会计划新增：分组功能，可定义分配网络段以及自定义组合漏洞环境。
> 
> 
> 
> 建议内置一些镜像，一键拉取启动

目前无法进行内置漏洞，只能将漏洞靶场信息内置。

**Comment by vc1** [comment]
就是这一个意思，现在是需要到hub上搜索，再复制粘贴名称，列表信息是可以内置的

**Comment by 0nise** [comment]
> 就是这个意思，现在是需要到hub上搜索，再复制粘贴名称，列表信息是可以内置的

预计在 0.2.3 版本发布时加入内置镜像

**Comment by 0nise** [comment]
功能已经全部实现，0.3.2.1 版本加入可视化编排功能。
