### ISSUE TITLE
任意文件读取漏洞，靶场如何支持？

### ISSUE THREAD

**Issue by aitalone** [fofapro/vulfocus#34]
**请简单描述一下需要改进/新增功能**：

**描述你想要的解决方案**：

**补充内容**：

**Comment by 0nise** [comment]
任意文件读取相关漏洞，没去可考虑的做法只有制定镜像的规范然后写入特定的目录中。

**Comment by 0nise** [comment]
默认已经支持任意文件读类型的漏洞，目前所有的 flag 会写入 /tmp 目录中
