### ISSUE TITLE
国内网络拉取dockerhub的镜像太慢

### ISSUE THREAD

**Issue by lovelyjuice** [fofapro/vulfocus#44]
国内网络拉取dockerhub的镜像太慢。

建议提供自定义registry的功能，从国内docker镜像拉取

**Comment by sysyz** [comment]
配置docker镜像站，https://www.daocloud.io/mirror

**Comment by sysyz** [comment]
> 国内网络拉取dockerhub的镜像太慢。
> 
> 建议提供自定义registry的功能，从国内docker镜像拉取

配置docker镜像站，https://www.daocloud.io/mirror

**Comment by lovelyjuice** [comment]
原来修改系统docker的registry就行了，之前一直以为它用的其它docker
