### ISSUE TITLE
redis-server服务问题

### ISSUE THREAD

**Issue by anonymity3712** [fofapro/vulfocus#46]
**报错信息**
redis未运行
**操作系统**： 
ubuntu19.10
**内核版本**：
Linux vul 5.3.0-46-generic
**Python 环境版本**：
python3.7
**Vulfocus 版本**：
2.1
**详细报错信息或堆栈报错信息**：
运行pip3 install -r requirements.txt后可以 依旧会提示redis-server未安装切redis服务未启动。重新执行apt-get install redis-server才可以

**Comment by 0nise** [comment]
该问题是在 Docker 中出现的吗？还是在没有使用 Docker 搭建系统时出现的？

**Comment by anonymity3712** [comment]
不是docker中的，是直接在本地搭建时遇见的

**Comment by 0nise** [comment]
主要问题是因为在安装时没有安装 redis 服务，目前已经在安装文档里面标明了。
