### ISSUE TITLE
增加靶场时常控制功能

### ISSUE THREAD

**Issue by sysyz** [fofapro/vulfocus#47]
建议增加靶场时长控制功能，可自定义设置靶场存活时间，存活时间可以设置为30分钟，60分，90分钟，120分钟。

有一个问题：docker环境部署的vulfocus，如何修改靶场默认的存活时间（30分钟）？

**Comment by 0nise** [comment]
系统从 `0.2.0` 版本就已经提供了控制容器的时间，默认时间为 `30` 分钟，达到 `30` 分钟之后会自动关闭。

设置方法：`系统管理` -> `系统配置` -> `镜像过期时间` 可进行配置，默认时间为 `1800s` （30 分钟），单位为秒。

**注：当设置为 `0` 之后，容器将用不关闭。**
