### ISSUE TITLE
前端显示不正确

### ISSUE THREAD

**Issue by Whippet0** [fofapro/vulfocus#54]
![1589787470(1)](https://user-images.githubusercontent.com/46486374/82187246-b603ea80-991e-11ea-87d7-9e5e16426a70.png)
在启动镜像容器后，指定的容器地址有时候跟虚拟机的地址并不相同，但是还是要访问虚拟机的地址才可以访问的到。

**Comment by 0nise** [comment]
访问地址是根据运行/启动时设置的 `VUL_IP` 参数来进行设置的，如果没有设置默认会选择本地/Docker 的一张网卡。
