### ISSUE TITLE
报错context canceled

### ISSUE THREAD

**Issue by Rooaw** [fofapro/vulfocus#56]
用的快速安装，run 命令后报错：
![image](https://user-images.githubusercontent.com/15188374/82537292-5efb5100-9b7c-11ea-90dc-9019c3a8eae8.png)
其他容器运行没问题

**Comment by 0nise** [comment]
方便提供一下所使用的操作系统、Docker 版本吗？

**Comment by Rooaw** [comment]
VUL_IP=0.0.0.0
