### ISSUE TITLE
是否支持多用户

### ISSUE THREAD

**Issue by adkinguzi** [fofapro/vulfocus#63]
**请简单描述一下需要改进/新增功能**：

**描述你想要的解决方案**：

**补充内容**：

**Comment by 0nise** [comment]
能详细说一下功能以及用途吗？

**Comment by adkinguzi** [comment]
增加多用户也是为了方便学习考核，比如每个用户可以单独开启靶场环境，管理员可以看到其他用户的的练习情况，靶场记录，评分，用时等等。

**Comment by 0nise** [comment]
目前靶场是兼容多租户的，可注册普通用户进行开启、使用靶场环境，互相不受影响，在管理员后台可以看到每一个用户所得得分数，使用记录。

**注：用户答题通过管理源后台会显示关闭状态，不可进行删除，如进行删除对应得用户会损失对应的得分**。

**Comment by adkinguzi** [comment]
I got it ! thanks guy
