### ISSUE TITLE
启动后未出现之前加入的镜像

### ISSUE THREAD

**Issue by lewisLANG** [fofapro/vulfocus#7]
正常启动后未出现之前加入的漏洞镜像
![2020-04-24_134845](https://user-images.githubusercontent.com/39106969/80179074-4d349580-8632-11ea-8d74-3d7c5475ddbe.png)

**Comment by 0nise** [comment]
默认初始化是没有漏洞镜像的，需要自己手动添加。

**Comment by 0nise** [comment]
默认初始化是没有漏洞镜像的，需要自己手动添加。
