### ISSUE TITLE
镜像升级

### ISSUE THREAD

**Issue by weske95** [fofapro/vulfocus#86]
请问您这个vulfocus镜像更新了之后，我的docker拉取的镜像该怎么去更新它

**Comment by 0nise** [comment]
重新 pull 就可以了

**Comment by weske95** [comment]
就是您发布的vulfocus的版本更新了之后，我这边vulfocus的docker镜像该怎么去升级它，重新拉取的话之前的用户的数据就丢失了

**Comment by 0nise** [comment]
首先进入容器将数据库db.sqlite文件拷贝出来，然后重新拉取镜像，启动时通过 -v 的方式将数据库挂载进去。

**Comment by weske95** [comment]
噢，好的，谢谢
