### ISSUE TITLE
启动漏洞镜像后台执行的命令

### ISSUE THREAD

**Issue by Betsy0** [fofapro/vulfocus#93]
你好，我自己做了个镜像，镜像的启动命令是：
docker run -itd --privileged -p 8080:8080 --name tomcat-pass-shell betsy0/tomcat /usr/sbin/init
然后我导入到vulfocus进行管理，发现无法启动，是我容器内的服务做的启动方式不对吗

**Comment by 0nise** [comment]
必须要通过 --privileged 的方式进行启动吗？

**Comment by Betsy0** [comment]
是的，因为对dockerfile不太熟悉，所以我是先pull一个镜像下来然后安装应用，tomcat是用systemctl管理启停的，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "r4v3zn"<notifications@github.com&gt;; 
发送时间: 2020年7月1日(星期三) 下午4:05
收件人: "fofapro/vulfocus"<vulfocus@noreply.github.com&gt;; 
抄送: "我可爱到发芽"<849310853@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [fofapro/vulfocus] 启动漏洞镜像后台执行的命令 (#93)





 
必须要通过 --privileged 的方式进行启动吗？

**Comment by 0nise** [comment]
vulfocus 在启动镜像时不会加入 --privileged 参数，可能由于这个问题导致无法正常启动。
